### ISSUE TITLE
Spiel startet nicht

### ISSUE THREAD

**Issue by Torom** [Torom/Cultures-Clone#15]
Wollte ein neues Spiel starten, keines laden

Fehlermeldung:

Exception in thread "main" exceptions.ActionNotPossibleException: Can Not Add Item. There Is An EObject In The Way!eObjects.Tree@36eec618
	at engine.Node.addItem(Node.java:137)
	at main.Test.test(Test.java:46)
	at main.Game.prepareForStart(Game.java:125)
	at main.Game.start(Game.java:138)
	at main.Global.initialize(Global.java:37)
	at main.Main.main(Main.java:11)

**Comment by Fundaran** [comment]
fixed
